### ISSUE TITLE
Timestamp precision

### ISSUE THREAD

**Issue by scrupeus** [rascol/Raspberry-Pi-PPS-Client#3]
Just wondering why the interrupt timestamps are `struct timeval` rather than `struct timespec`? (i.e. microsecond rather than nanosecond precision)  See [`pps_interrupt1`](https://github.com/rascol/Raspberry-Pi-PPS-Client/blob/c6b58023d760f1bbd9c4ee822e91f7c2b9ade801/driver/gps-pps-io.c#L477) for example.

Wouldn't a nanosecond timestamp reduce quantisation noise?  I appreciate the client code would need changes but I can't see an obvious reason for using microsecond precision.

**Comment by rascol** [comment]
The original design philosophy for pps-client was to synchronize to the PPS without bypassing NTP simply because it might be the only available way to get whole seconds. That required using adjtimex() which contains the NTP time adjustment algorithm. Unfortunately, adjtimex() only knows about time to an accuracy of microseconds. So nanosecond precision would be rounded to microseconds anyway.

**Comment by scrupeus** [comment]
Using nanosecond precision would reduce noise in your calculations and potentially affect the required adjustments (some may be eliminated, others may be added).  But I agree it wouldn't be a big improvement.

Checking `man adjtimex`, nanosecond precision is enabled by including `ADJ_NANO` in the `modes` field.  I also noted that the comments in `timex.h` for `struct timex` are misleading by only mentioning microseconds, but `ADJ_NANO` is in the header.

Please note that I'm not suggesting you (or anyone else) necessarily change the code to use nanosecond precision; not much more would be gained with the current code.  I was just curious as to why the decision had been made, which you've answered.
